
EnvironmentNameNotFound: Could not find conda environment: myenv
You can list all discoverable environments with `conda info --envs`.


Traceback (most recent call last):
  File "/home/ids/ext-6401/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ids/ext-6401/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ssd/ext-6401/PSCC-IPParis-Challenge/src/train.py", line 51, in <module>
    train_files = dataset.get_train_files()
  File "/home/ssd/ext-6401/PSCC-IPParis-Challenge/src/dataset.py", line 9, in get_train_files
    for img,label in zip(os.listdir(vol_path), os.listdir(seg_path)):
OSError: [Errno 116] Stale file handle: '/tsi/data_education/data_challenge/train/volume'
